#!/usr/bin/env bash
# Install a cron job that runs the arborstats jobs (All Cells, All BCs, All Glia)
# one after another at midnight every other day.
#
# Usage:
#   ./setup_arborstats_cron.sh              # install / update the cron job
#   ./setup_arborstats_cron.sh --uninstall  # remove the cron job
#
# Run it from the environment where `arborstats` is installed (venv/conda
# activated), or set ARBORSTATS_BIN to its full path.

set -euo pipefail

CRON_TAG="# arborstats-every-other-night"
RUNNER="$HOME/.local/bin/arborstats_every_other_night.sh"
LOG_DIR="$HOME/arborstats_logs"

if [[ "${1:-}" == "--uninstall" ]]; then
    crontab -l 2>/dev/null | grep -vF "$CRON_TAG" | crontab - || true
    echo "Removed cron job. Runner script left at $RUNNER"
    exit 0
fi

# cron runs with a minimal PATH, so pin the absolute path now.
ARBORSTATS_BIN="${ARBORSTATS_BIN:-$(command -v arborstats || true)}"
if [[ -z "$ARBORSTATS_BIN" || ! -x "$ARBORSTATS_BIN" ]]; then
    echo "error: arborstats not found. Activate its environment or set ARBORSTATS_BIN." >&2
    exit 1
fi

mkdir -p "$(dirname "$RUNNER")" "$LOG_DIR"

cat > "$RUNNER" <<EOF
#!/usr/bin/env bash
# Generated by setup_arborstats_cron.sh. Runs the arborstats jobs sequentially.
set -uo pipefail

ARBORSTATS="$ARBORSTATS_BIN"
export PATH="$(dirname "$ARBORSTATS_BIN"):\$PATH"
LOG_DIR="$LOG_DIR"
OUTPUT_DIR="\$HOME/gcs-bucket"
# SQLite is written locally (gcsfuse handles SQLite writes poorly) and copied
# to the bucket once all runs finish.
SQLITE_FILE="\$HOME/arbor_stats_op/arbor_stats.sqlite3"
SHEET_ID="1o4i53h92oyzsBc8jEWKmF8ZnfyXKXtFCTaYSecs8tBk"

# Cron fires every midnight; only run on even days since the epoch so the
# every-other-day rhythm doesn't break at month boundaries (unlike */2).
if (( \$(date +%s) / 86400 % 2 != 0 )) && [[ "\${1:-}" != "--force" ]]; then
    exit 0
fi

LOG_FILE="\$LOG_DIR/arborstats_\$(date +%Y-%m-%d).log"
exec >>"\$LOG_FILE" 2>&1

# Skip if a previous run is still going.
exec 9>"\$LOG_DIR/.arborstats.lock"
if ! flock -n 9; then
    echo "\$(date "+%F %T") previous run still active, skipping"
    exit 0
fi

if ! mountpoint -q "\$OUTPUT_DIR"; then
    echo "\$(date "+%F %T") \$OUTPUT_DIR is not mounted, aborting"
    exit 1
fi

COMMON_ARGS=(
    --google-sheet-id "\$SHEET_ID"
    --read-columns 'Latest SegID' 'Status' 'Cell Class'
    --segid-col 'Latest SegID'
    --dtypes 'Latest SegID=string' 'Status=string' 'Cell Class=string'
    --output-dir "\$OUTPUT_DIR"
    -j 18
    --new-only
    --arbor-stats-only
    --stats-method morphopy
    --export-sqlite
    --export-file "\$SQLITE_FILE"
)

status=0
run() {
    local name="\$1"; shift
    echo "===== \$(date "+%F %T") START \$name ====="
    local rc=0
    "\$ARBORSTATS" "\${COMMON_ARGS[@]}" "\$@" || rc=\$?
    if (( rc == 0 )); then
        echo "===== \$(date "+%F %T") DONE \$name ====="
    else
        echo "===== \$(date "+%F %T") FAILED \$name (exit \$rc) ====="
        status=1
    fi
}

run "All Cells" --gid 1690313708
run "All BCs"   --gid 1528488002
run "All Glia"  --gid 2051269861

if [[ -f "\$SQLITE_FILE" ]]; then
    if cp "\$SQLITE_FILE" "\$OUTPUT_DIR/"; then
        echo "\$(date "+%F %T") copied \$SQLITE_FILE to \$OUTPUT_DIR/"
    else
        echo "\$(date "+%F %T") FAILED to copy \$SQLITE_FILE to \$OUTPUT_DIR/"
        status=1
    fi
fi

exit \$status
EOF
chmod +x "$RUNNER"

# Replace any previous entry, then add the new one (daily at 00:00; the runner
# skips odd days).
{
    crontab -l 2>/dev/null | grep -vF "$CRON_TAG" || true
    echo "0 0 * * * $RUNNER $CRON_TAG"
} | crontab -

echo "Installed cron job:"
crontab -l | grep -F "$CRON_TAG"
echo "Runner: $RUNNER"
echo "Logs:   $LOG_DIR"
echo "Test now with: $RUNNER --force"
